apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: mqace
  namespace: mq
  labels:
    name: docker-build
spec:
  source:
    dockerfile: |-
      FROM cp.icr.io/cp/icp4i/mq/ibm-mqadvanced-server-integration:9.1.5.0-r1-amd64
      RUN echo -e "\
      DEFINE QLOCAL('AccidentIn') \n\
      DEFINE QLOCAL('AccidentOut') \n\
      DEFINE QLOCAL('BumperIn') \n\
      DEFINE QLOCAL('BumperOut') \n\
      DEFINE QLOCAL('CrumpledIn') \n\
      DEFINE QLOCAL('CrumpledOut') \n\
      DEFINE CHANNEL(ACE_SVRCONN) CHLTYPE(SVRCONN) TRPTYPE(TCP) SSLCIPH('ECDHE_RSA_AES_128_CBC_SHA256') SSLCAUTH(OPTIONAL) MCAUSER('mqm') \n\
      SET CHLAUTH(ACE_SVRCONN) TYPE(BLOCKUSER) ACTION(REPLACE) USERLIST("nobody") \n\
      REFRESH SECURITY" > /etc/mqm/aceldap.mqsc
      RUN cat /etc/mqm/aceldap.mqsc
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: "DockerImage"
        name: "cp.icr.io/cp/icp4i/mq/ibm-mqadvanced-server-integration:9.1.4.0-r1-amd64"
      pullSecret:
        name: ibm-entitlement-key
  output:
    to:
      kind: ImageStreamTag
      name: 'mqace:latest-amd64'
