# © Copyright IBM Corporation 2017, 2019
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- include "sch.config.init" (list . "ibm-mq.sch.chart.config.values") }}
{{ $fullName := include "sch.names.fullName" (list .) }}
{{ $standardLabel := include "sch.metadata.labels.standard" (list . "") }}
{{ $configLabel := include "ibm-mq.sch.chart.config.metadata.labels" . }}
{{ $appName := include "sch.names.appName" (list .) }}
{{ $releaseName := .Release.Name }}
{{ $statefulSetName := include "sch.names.statefulSetName" (list .) }}
{{- if .Values.scaling.enabled }}
{{- $replicaCount := .Values.scaling.replicas | int }}
{{- range $index0 := until $replicaCount -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-{{ $index0 }}
  labels:
{{ $standardLabel | indent 4 }}
{{- $configLabel | indent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 1414
    name: qmgr
  selector:
    app: "{{ $appName }}"
    release: "{{ $releaseName }}"
    mqInstance: {{ $statefulSetName }}-{{ $index0 }}
---
{{- end }}
{{- else }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sch.names.fullName" (list .) }}
  labels:
{{ $standardLabel | indent 4 }}
{{- $configLabel | indent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 1414
    name: qmgr
  selector:
    app: "{{ $appName }}"
    release: "{{ .Release.Name }}"
{{- end }}
