apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: mqldap
  namespace: mq
  labels:
    name: docker-build
spec:
  source:
    dockerfile: |-
      FROM cp.icr.io/cp/icp4i/mq/ibm-mqadvanced-server-integration:9.1.3.0-r4-amd64
      RUN echo $'DEFINE QLOCAL(Q1) \n\
      DEFINE CHANNEL(QMLDAP_SVRCONN) CHLTYPE(SVRCONN) TRPTYPE(TCP) SSLCIPH("ECDHE_RSA_AES_128_CBC_SHA256") SSLCAUTH(OPTIONAL)  \n\
      SET CHLAUTH(QMLDAP_SVRCONN) TYPE(BLOCKUSER) ACTION(REPLACE) USERLIST("nobody") \n\
      DEFINE AUTHINFO(USE.LDAP) AUTHTYPE(IDPWLDAP) CONNAME("ldap-service.ldap(389)") LDAPUSER("cn=admin,dc=ibm,dc=com") LDAPPWD("admin") SECCOMM(NO)       USRFIELD("uid") SHORTUSR("uid") BASEDNU("ou=people,dc=ibm,dc=com") AUTHORMD(SEARCHGRP) BASEDNG("ou=groups,dc=ibm,dc=com") GRPFIELD("cn") CLASSGRP("groupOfUniqueNames") FINDGRP("uniqueMember")\n\
      ALTER QMGR CONNAUTH(USE.LDAP)\n\
      REFRESH SECURITY\n\
      SET AUTHREC OBJTYPE(QMGR) GROUP("apps") AUTHADD(ALL)\n\
      SET AUTHREC PROFILE("Q1") OBJTYPE(QUEUE) GROUP("apps") AUTHADD(ALL)\n\
      REFRESH SECURITY' > /etc/mqm/ldap.mqsc
      RUN cat /etc/mqm/ldap.mqsc
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: "DockerImage"
        name: "cp.icr.io/cp/icp4i/mq/ibm-mqadvanced-server-integration:9.1.3.0-r4-amd64"
      pullSecret:
        name: entitled-registry
  output:
    to:
      kind: ImageStreamTag
      name: 'mqldap:latest-amd64'
