kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: mq-traffic-mq-ldap-ibm-mq-qm
  namespace: mq
spec:
  host: qmldap5f-svrconn.chl.mq.ibm.com
  to:
    kind: Service
    name: mq-ldap-ibm-mq
  port:
    targetPort: 1414
  tls:
    termination: passthrough
  wildcardPolicy: None
